AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  resize image

  SAM Template for sam-resize-image

Globals:
  Function:
    Timeout: 10

Parameters:
  Env:
    Type: String
    Description: Environment
    AllowedValues: [prod, stg, dev]
    Default: dev

Resources:
  ResizeImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: resize-image/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        ResizeImage:
          Type: Api
          Properties:
            RestApiId: !Ref ImageProcessingApi
            Path: /{type}/{size}/{directory}/{contentId}/{subDirectory}/{filename}
            Method: get

  ImageProcessingApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Env
      BinaryMediaTypes: [
        "application~1octet-stream",
        "image~1png",
        "image~1jpeg",
        "image~1gif",
        "image~1webp"
      ]
      DefinitionBody:
        swagger: 2.0
        info:
          title: !Sub image-processing-api-${Env}
          description: !Sub image-processing-api-${Env}
          version: 1.0.0
        schemes:
          - https
        basePath: !Sub /${Env}
        paths:
          /{type}/{size}/{directory}/{contentId}/{subDirectory}/{filename}:
            get:
              produces:
                - application/json
              responses:
                "200":
                  description: "200 response"
                "500":
                  description: "500 response"
              x-amazon-apigateway-integration:
                httpMethod: POST
                uri:
                  !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ResizeImageFunction.Arn}/invocations
                responses:
                  default:
                    statusCode: "200"
                type: aws_proxy
        x-amazon-apigateway-binary-media-types: ['application/octet-stream', 'image/jpeg', 'image/png', 'image/gif', 'image/webp']

Outputs:
  ImageProcessingApi:
    Description: Image Processing Api Endpoint
    Value: !Ref ImageProcessingApi
  ResizeImageFunction:
    Description: "Resize Image Lambda Function ARN"
    Value: !Ref ResizeImageFunction
  ResizeImageFunctionIamRole:
    Description: "Implicit IAM Role created for Resize Image function"
    Value: !GetAtt ResizeImageFunctionRole.Arn
