AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  resize image

  Sample SAM Template for sam-app
  
Globals:
  Function:
    Timeout: 10

Parameters:
  Env:
    Type: String
    Description: Environment
    AllowedValues: [prod, stg, dev]
    Default: dev

Resources:
  ResizeImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: resize-image/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        ResizeImage:
          Type: Api
          Properties:
            RestApiId: !Ref ImageProcessingApi
            Path: /{type}/{size}/{directory}/{contentId}/{subDirectory}/{filename}
            Method: get

  ImageProcessingApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Env
      DefinitionBody:
        swagger: 2.0
        info:
          title: !Sub image-processing-api-${Env}
          description: !Sub image-processing-api-${Env}
          version: 1.0.0
        schemes:
          - https
        basePath: !Sub /${Env}
        x-amazon-apigateway-binary-media-types: ['application/octet-stream', 'image/jpeg', 'image/png', 'image/gif', 'image/webp']


Outputs:
  ImageProcessingApi:
    Description: Image Processing Api Endpoint
    Value: !Ref ImageProcessingApi
  ResizeImageFunction:
    Description: "Resize Image Lambda Function ARN"
    Value: !GetAtt ResizeImageFunction.Arn
  ResizeImageFunctionIamRole:
    Description: "Implicit IAM Role created for Resize Image function"
    Value: !GetAtt ResizeImageFunctionRole.Arn
